### ISSUE TITLE
i2creg Open fail

### ISSUE THREAD

**Issue by wangyongneng01** [MichaelS11/go-ads#1]
你好，我在调试您项目中的demo时，出现了一个bug
panic: runtime error: invalid memory address or nil pointer dereference

> i2creg: no bus found; did you forget to call Init()?

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10962e3]

i2creg.go 中的Open方法提示没有初始化。
func Open(name string) (i2c.BusCloser, error) {
	var r *Ref
	var err error
	func() {
		mu.Lock()
		defer mu.Unlock()
		if len(byName) == 0 {
			err = errors.New("i2creg: no bus found; did you forget to call Init()?")
			return
		}
		if len(name) == 0 {
			r = getDefault()
			return
		}
		// Try by name, by alias, by number.
		if r = byName[name]; r == nil {
			if r = byAlias[name]; r == nil {
				if i, err2 := strconv.Atoi(name); err2 == nil {
					r = byNumber[i]
				}
			}
		}
	}()
	if err != nil {
		return nil, err
	}
	if r == nil {
		return nil, errors.New("i2creg: can't open unknown bus: " + strconv.Quote(name))
	}
	return r.Open()
}
请问下，这边怎么操作

**Comment by MichaelS11** [comment]
Only speak English, but using Google translate.

Maybe try the following All example and see if the device is showing up?

https://godoc.org/periph.io/x/periph/conn/i2c/i2creg#example-All

What is the output?

**Comment by MichaelS11** [comment]
Hopefully you figured it out.
