### ISSUE TITLE
Select different inputs

### ISSUE THREAD

**Issue by elliotbailey13** [MichaelS11/go-ads#2]
I would like to select different inputs but it would seem it's hardcoded to A0. I would like to contribute but I do not have access to the repo.

**Comment by MichaelS11** [comment]
Did you mean these options?
https://github.com/MichaelS11/go-ads/blob/4238d785f0981095af7ac4fd01546379ef8c8ab1/globals.go#L21-L29

If not, what do you mean by hardcoded to A0?

**Comment by elliotbailey13** [comment]
Correct, those are the options I'm talking about. Looks like there is an easy way to change Gain and Data Rates but not inputs.

**Comment by MichaelS11** [comment]
The options above lets you choose from A0 to A3 inputs.

**Comment by elliotbailey13** [comment]
Please pardon my GoLang n00b level. Would you mind giving me an example?

**Comment by MichaelS11** [comment]
Sorry, you are correct, my bad. Those options are not exposed. Ok, if I make a change can you test it?

**Comment by elliotbailey13** [comment]
Totally! I'll be able to test it tonight.

**Comment by MichaelS11** [comment]
Cool, will have something for you soon.

**Comment by MichaelS11** [comment]
Please test the input branch.

**Comment by elliotbailey13** [comment]
Looks like it worked perfectly! Thank you very much! You are a gentleman and a scholar! I'll list some details of the hardware below to give you an idea of what it was working on.

Raspberry Pi Model - Zero W Rev 1.1
OS - Raspbian 10 (buster)
Kernel - 4.19.75+
Go version - 1.13.1
Sensor - [ADS1115](https://www.adafruit.com/product/1085)

**Comment by MichaelS11** [comment]
Wonderful, glad it worked out. Merged into master.
