### ISSUE TITLE
Why does this give different results from the Adafruit Python lib?

### ISSUE THREAD

**Issue by kramer65** [MichaelS11/go-ads#4]
I'm building an autonomous boat, in which I now want to add water sensors, to get a notification when water is entering the boat.

I can read out my ADS1115 perfectly using [the Adafruit Python lib](https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15). I just the example in the readme and it prints out the following (the water sensor is dry):
```
  raw       v
    1   0.000
    1   0.000
    1   0.000
```
But since my boat logic is written in Golang, I'd like to use your lib. So I fired up the [ReadRetry example](https://github.com/MichaelS11/go-ads#readretry-example) from the readme, but to my surprise it prints out the following:
```
result: 62453
volts: 9.529862361522262
psi: 3405.7504501480144 
```

I tried all different ConfigGains, but they all give comparable results (Voltages between 8.6 and 9.9). I don't know if it matters, but I'm using a Pi Zero.

Also; I'm trying to read out channel 0 of the four channels available on the ADS1115. I don't understand how I can define which channel to read though.

**Comment by kramer65** [comment]
Ok, after some fiddling around (switching connectors and making the sensor wet and dry) I found that I'm actually reading out channel "A1" on the ADS1115. The voltage still differs from the results in Python, but I just need to know whether the sensor is wet at all, so the results so far are good enough for my use case. It would be interesting to know where this difference comes from though.

And also, I still don't understand how to select either one of the four channels though (A0, A1, A2 or A3). Maybe this could be added to the readme?

**Comment by MichaelS11** [comment]
It is not in the readme because it is more about how the chip works rather then how the code works. The channel information can be found in the documentation about the chip or other places on the internet.

Here is where the settings are located in the code if that helps:
https://github.com/MichaelS11/go-ads/blob/master/globals.go#L25-L40

**Comment by MichaelS11** [comment]
@kramer65 All good? Can you close this?

**Comment by kramer65** [comment]
Good morning @MichaelS11. I was actually sleeping, we tend to do that at night in Europe. I guess you are doing the same at this moment..  ;-) 


Thanks for your answer, that clears up a lot. I added the line below and it now seems to work a lot better:

    ads1.SetConfigInputMultiplexer(ads.ConfigInputMultiplexerSingle1)

I still see differences in output between the Python implementation by adafruit and your Go implementation, but they are reduced to a difference of about 0.2V, which is for my use case not a problem. So I'll be happily using your code in what is called "Project Whisky". The aim of it is building an autonomous solar powered boat that sails across the North sea from Amsterdam to Scotland and brings back a fine bottle of Scotch Whisky.

One more thing. Despite your objections, I would still highly recommend adding a couple lines about the Multiplexer in the readme. For starters, I don't even know what a "multiplexer" is (I'm a hobbyist though). I'm just saying that it would greatly improve the usability of your library if you add a couple simple lines saying something like.

```
The ADS1115 has four channels, or "multiplexers" from which it can read the analog input. You can switch between those multiplexers using this for readying out single channels:

    ads1.SetConfigInputMultiplexer(ads.ConfigInputMultiplexerSingle1) 

Or this for reading out the differentials between channel 0 and 1 (which is the default):

    ads1.SetConfigInputMultiplexer(ads.ConfigInputMultiplexerDifferential01) 
    
```

Anyway, thanks for creating this lib and I wish you a beautiful day!

**Comment by MichaelS11** [comment]
@kramer65 

Sounds like a very cool project! If you have a link to blog post or something like that, welcome to post it in this thread/issue.

I appreciate your feedback. I am curious, did you read through the information that was linked on the readme? https://learn.adafruit.com/adafruit-4-channel-adc-breakouts/
What about the golang docs? https://godoc.org/github.com/MichaelS11/go-ads
Would have either of those provided the information you were looking for?
