### ISSUE TITLE
Non global constants

### ISSUE THREAD

**Issue by dbboyd17** [MichaelS11/go-ads#5]
Hi Miachel

There are still a number of constants defined in the globals package with are not externally accessible
e.g. configOperationSingle

I can understand why some constants in the globals file are not visible, such as register pointers since these are specific to the device and are internal to the operation of the package.
However, configuration options should really be externally visible so that they can be set.
This would apply to the following (at least)
configOperationSingle
configOperatingModeSingle
configComparatorModeTraditional
configComparatorPolarityLow
configLatchingComparatorOff
configComparatorQueueOff

At present I have modified the package to work around this, but this is obviously not a good idea!

Any chance of making ALL the  relevant config options available externally?

Thanks.

**Comment by dbboyd17** [comment]
I should have said that the globals are not exported, which is what I meant by 'not externally accessible'

**Comment by MichaelS11** [comment]
I just did not need them or did not understand how they would be useful, so I thought no need to cluster up what was visible. If you need to use them, I welcome a good PR that would make them visible. Example: https://github.com/MichaelS11/go-ads/pull/3

**Comment by dbboyd17** [comment]
Ok - I will need to see if I can minimize the changes, as I did add in an exported function to the interface that can probably be removed. I am about to go on leave, so I may not get back to this for a week or so.

**Comment by MichaelS11** [comment]
Welcome a good PR for this. Closing the issue.
